kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-storage
  namespace: monitoring
  labels:
    app: rabbitmq
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/var/k8s/pvs/rabbitmq/"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gh02
