kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: rabbitmq
  ports:
  - name: http
    port: 15672
  - name: epmd
    port: 4369
  - name: amqp
    port: 5672
  - name: rabbitmq-dist
    port: 25672
---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: rabbitmq-mgnt
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
   - name: http
     port: 15672
  selector:
    app: rabbitmq
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: default
spec:
  serviceName: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      serviceAccountName: rabbitmq
      terminationGracePeriodSeconds: 10
      containers:        
      - name: rabbitmq
        image: arm32v7/rabbitmq:3.7.8-management
        volumeMounts:
          - name: rabbitmq
            mountPath: /var/lib/rabbitmq
          - name: config-volume
            mountPath: /etc/rabbitmq
        ports:
          - name: http
            protocol: TCP
            containerPort: 15672
          - name: amqp
            protocol: TCP
            containerPort: 5672
          - name: epmd
            protocol: TCP
            containerPort: 4369
          - name: rabbitmq-dist
            protocol: TCP
            containerPort: 25672
        livenessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 10
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: RABBITMQ_USE_LONGNAME
            value: "true"
          # See a note on cluster_formation.k8s.address_type in the config file section
          - name: RABBITMQ_NODENAME
            value: "rabbit@$(POD_NAME).rabbitmq.default.svc.cluster.local"
          - name: K8S_SERVICE_NAME
            value: "rabbitmq"
          - name: RABBITMQ_ERLANG_COOKIE
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: "erlang-cookie"
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
        - name: config-volume
          configMap:
            name: rabbitmq-config
            items:
            - key: rabbitmq.conf
              path: rabbitmq.conf
            - key: enabled_plugins
              path: enabled_plugins
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      selector:
        matchLabels:
          app: rabbitmq
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 2Gi
