kind: PersistentVolume
apiVersion: v1
metadata:
  name: influxdb-storage
  namespace: monitoring
  labels:
    app: influxdb
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/var/k8s/pvs/influxdb/"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gh03
