kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-storage
  namespace: monitoring
  labels:
    app: grafana
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/var/k8s/pvs/grafana/"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gh03
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-storage
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

