apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: web
  selector:
    app: grafana
