apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rpi-moisture-sensor
  namespace: default
spec:
  selector:
    matchLabels:
      app: rpi-moisture-sensor
  template:
    metadata:
      labels:
        app: rpi-moisture-sensor
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: rpi-sensors
                operator: In
                values:
                - soil_moisture
      containers:
      - name: rpi-moisture-sensor
        image: drunkinfant/rpi-moisture-sensor:0.3.0
        args: ["/bin/rpi-moisture-sensor", "--config", "/etc/sensors/$(RPI_NAME).toml", "--interval", "$(INTERVAL)", "rabbitmq", "--host", "rabbitmq:5672", "--exchange", "$(RABBITMQ_EXCHANGE)"]
        securityContext:
          privileged: true
        volumeMounts:
          - name: config-volume
            mountPath: /etc/sensors
        env:
        - name: RPI_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: RABBITMQ_EXCHANGE
          value: "sensor_samples"
        - name: INTERVAL
          value: "60"
        resources:
          limits:
            cpu: 100m
            memory: 32Mi
          requests:
            cpu: 100m
            memory: 16Mi
      volumes:
        - name: config-volume
          configMap:
            name: rpi-moisture-sensor-config
