apiVersion: v1
kind: ConfigMap
metadata:
  name: rpi-moisture-sensor-config
  namespace: default
data:
  gh03.toml: |
      [sensors]
      moist01.sensor_type = 'soil_moisture'
      moist01.pwr_pin = 17
      moist01.val_pin = 27
      moist01.pwr_wait = 1500
      moist01.interval = 60
  gh02.toml: |
      [sensors]
      moist02.sensor_type = 'soil_moisture'
      moist02.pwr_pin = 17
      moist02.val_pin = 27
      moist02.pwr_wait = 1500
      moist02.interval = 60
